"""
Terraform HCL Generator

Generates Terraform HCL code from converted CloudFormation resources.
"""

import json
import re
from typing import Any, Dict, List, Optional, Set, Tuple

from cf2tf.resource_mappings import (
    RESOURCE_TYPE_MAPPING,
    PROPERTY_MAPPINGS,
    get_terraform_resource_type,
)
from cf2tf.resource_mappings.aws_mappings import (
    PSEUDO_PARAMETER_MAPPING,
    RESOURCE_REF_MAPPING,
    RESOURCE_GETATT_MAPPING,
    transform_tags,
    transform_security_group_rules,
)


class TerraformGenerator:
    """
    Generates Terraform HCL code from parsed CloudFormation data.

    Handles:
    - Resource conversion
    - Variable generation from Parameters
    - Output generation
    - Locals for Mappings
    - Data sources for pseudo-parameters
    """

    def __init__(self):
        self.resources: Dict[str, Any] = {}
        self.parameters: Dict[str, Any] = {}
        self.outputs: Dict[str, Any] = {}
        self.mappings: Dict[str, Any] = {}
        self.conditions: Dict[str, Any] = {}
        self.converted_resources: Dict[str, Dict[str, Any]] = {}
        self.required_data_sources: Set[str] = set()
        self.resource_name_mapping: Dict[str, str] = {}

    def generate(
        self,
        resources: Dict[str, Any],
        parameters: Dict[str, Any],
        outputs: Dict[str, Any],
        mappings: Dict[str, Any],
        conditions: Dict[str, Any],
    ) -> str:
        """
        Generate complete Terraform configuration.

        Args:
            resources: CloudFormation Resources section
            parameters: CloudFormation Parameters section
            outputs: CloudFormation Outputs section
            mappings: CloudFormation Mappings section
            conditions: CloudFormation Conditions section

        Returns:
            Complete Terraform HCL code as string
        """
        self.resources = resources
        self.parameters = parameters
        self.outputs = outputs
        self.mappings = mappings
        self.conditions = conditions

        # Build resource name mapping (CFN name -> Terraform name)
        self._build_resource_name_mapping()

        # Generate each section
        sections = []

        # Terraform and provider blocks
        sections.append(self._generate_terraform_block())
        sections.append(self._generate_provider_block())

        # Data sources (if needed)
        data_sources = self._generate_data_sources()
        if data_sources:
            sections.append(data_sources)

        # Variables from Parameters
        variables = self._generate_variables()
        if variables:
            sections.append(variables)

        # Locals from Mappings
        locals_block = self._generate_locals()
        if locals_block:
            sections.append(locals_block)

        # Resources
        for resource_name, resource_data in resources.items():
            resource_block = self._generate_resource(resource_name, resource_data)
            if resource_block:
                sections.append(resource_block)

        # Outputs
        outputs_block = self._generate_outputs()
        if outputs_block:
            sections.append(outputs_block)

        return "\n".join(sections)

    def _build_resource_name_mapping(self):
        """Build mapping from CFN resource names to Terraform resource names."""
        for cfn_name, resource_data in self.resources.items():
            tf_name = self._to_terraform_name(cfn_name)
            self.resource_name_mapping[cfn_name] = tf_name

    def _to_terraform_name(self, name: str) -> str:
        """Convert a CloudFormation resource name to a valid Terraform name."""
        # Convert CamelCase to snake_case
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
        snake_case = re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()
        # Remove any invalid characters
        clean_name = re.sub(r"[^a-z0-9_]", "_", snake_case)
        # Remove consecutive underscores
        clean_name = re.sub(r"_+", "_", clean_name)
        return clean_name.strip("_")

    def _generate_terraform_block(self) -> str:
        """Generate the terraform configuration block."""
        return '''# =============================================================================
# Terraform Configuration
# Generated by CF2TF - CloudFormation to Terraform Migration Framework
# =============================================================================

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0.0"
    }
  }
}
'''

    def _generate_provider_block(self) -> str:
        """Generate the AWS provider block."""
        return '''# =============================================================================
# Provider Configuration
# =============================================================================

provider "aws" {
  # Configure your AWS region here or use environment variables
  # region = "us-east-1"
}
'''

    def _generate_data_sources(self) -> str:
        """Generate required data sources."""
        data_sources = []

        # Check what pseudo-parameters are used
        template_str = json.dumps(self.resources)

        if "AWS::AccountId" in template_str or "aws_caller_identity" in str(self.required_data_sources):
            data_sources.append('''data "aws_caller_identity" "current" {}''')

        if "AWS::Region" in template_str or "aws_region" in str(self.required_data_sources):
            data_sources.append('''data "aws_region" "current" {}''')

        if "AWS::Partition" in template_str or "AWS::URLSuffix" in template_str:
            data_sources.append('''data "aws_partition" "current" {}''')

        if not data_sources:
            return ""

        return '''# =============================================================================
# Data Sources
# =============================================================================

''' + "\n\n".join(data_sources) + "\n"

    def _generate_variables(self) -> str:
        """Generate Terraform variables from CloudFormation parameters."""
        if not self.parameters:
            return ""

        variables = []
        variables.append('''# =============================================================================
# Variables (from CloudFormation Parameters)
# =============================================================================
''')

        for param_name, param_data in self.parameters.items():
            var_name = self._to_terraform_name(param_name)
            var_block = self._generate_variable(var_name, param_data)
            variables.append(var_block)

        return "\n".join(variables)

    def _generate_variable(self, name: str, param_data: Dict[str, Any]) -> str:
        """Generate a single variable block."""
        lines = [f'variable "{name}" {{']

        # Description
        description = param_data.get("Description", "")
        if description:
            lines.append(f'  description = "{self._escape_string(description)}"')

        # Type mapping
        cfn_type = param_data.get("Type", "String")
        tf_type = self._map_parameter_type(cfn_type)
        lines.append(f"  type        = {tf_type}")

        # Default value
        default = param_data.get("Default")
        if default is not None:
            default_str = self._format_value(default, tf_type)
            lines.append(f"  default     = {default_str}")

        # Validation for AllowedValues
        allowed_values = param_data.get("AllowedValues")
        if allowed_values:
            values_str = ", ".join(f'"{v}"' for v in allowed_values)
            allowed_values_str = ", ".join(str(v) for v in allowed_values)
            lines.append(f"""
  validation {{
    condition     = contains([{values_str}], var.{name})
    error_message = "Value must be one of: {allowed_values_str}"
  }}""")

        # Validation for AllowedPattern
        allowed_pattern = param_data.get("AllowedPattern")
        if allowed_pattern:
            lines.append(f"""
  validation {{
    condition     = can(regex("{self._escape_string(allowed_pattern)}", var.{name}))
    error_message = "Value must match pattern: {self._escape_string(allowed_pattern)}"
  }}""")

        # Sensitive for NoEcho
        if param_data.get("NoEcho", False):
            lines.append("  sensitive   = true")

        lines.append("}")
        return "\n".join(lines) + "\n"

    def _map_parameter_type(self, cfn_type: str) -> str:
        """Map CloudFormation parameter type to Terraform type."""
        type_mapping = {
            "String": "string",
            "Number": "number",
            "List<Number>": "list(number)",
            "CommaDelimitedList": "list(string)",
            "AWS::SSM::Parameter::Value<String>": "string",
            "AWS::EC2::AvailabilityZone::Name": "string",
            "AWS::EC2::Image::Id": "string",
            "AWS::EC2::Instance::Id": "string",
            "AWS::EC2::KeyPair::KeyName": "string",
            "AWS::EC2::SecurityGroup::GroupName": "string",
            "AWS::EC2::SecurityGroup::Id": "string",
            "AWS::EC2::Subnet::Id": "string",
            "AWS::EC2::VPC::Id": "string",
            "AWS::Route53::HostedZone::Id": "string",
            "List<AWS::EC2::Subnet::Id>": "list(string)",
            "List<AWS::EC2::SecurityGroup::Id>": "list(string)",
            "List<AWS::EC2::AvailabilityZone::Name>": "list(string)",
        }
        return type_mapping.get(cfn_type, "string")

    def _generate_locals(self) -> str:
        """Generate locals block from CloudFormation mappings."""
        if not self.mappings:
            return ""

        lines = ['''# =============================================================================
# Local Values (from CloudFormation Mappings)
# =============================================================================

locals {''']

        for mapping_name, mapping_data in self.mappings.items():
            tf_name = self._to_terraform_name(mapping_name)
            formatted = json.dumps(mapping_data, indent=4)
            # Convert JSON to HCL-style
            formatted = formatted.replace('": ', " = ").replace('"', "")
            lines.append(f"  {tf_name} = {formatted}")

        lines.append("}")
        return "\n".join(lines) + "\n"

    def _generate_resource(self, cfn_name: str, resource_data: Dict[str, Any]) -> str:
        """Generate a Terraform resource block."""
        cfn_type = resource_data.get("Type", "")
        tf_type = get_terraform_resource_type(cfn_type)

        if not tf_type:
            return self._generate_unsupported_resource_comment(cfn_name, cfn_type, resource_data)

        tf_name = self.resource_name_mapping[cfn_name]
        properties = resource_data.get("Properties", {})
        condition = resource_data.get("Condition")
        depends_on = resource_data.get("DependsOn", [])

        lines = [f'resource "{tf_type}" "{tf_name}" {{']

        # Convert properties
        converted_props = self._convert_properties(cfn_type, properties)
        for prop_name, prop_value in converted_props.items():
            prop_lines = self._format_property(prop_name, prop_value, indent=2)
            lines.extend(prop_lines)

        # Add count for conditional resources
        if condition:
            lines.insert(1, f"  count = local.{self._to_terraform_name(condition)} ? 1 : 0")

        # Add depends_on
        if depends_on:
            if isinstance(depends_on, str):
                depends_on = [depends_on]
            deps = []
            for dep in depends_on:
                if dep in self.resource_name_mapping:
                    dep_resource = self.resources.get(dep, {})
                    dep_type = get_terraform_resource_type(dep_resource.get("Type", ""))
                    if dep_type:
                        deps.append(f"{dep_type}.{self.resource_name_mapping[dep]}")
            if deps:
                deps_str = ", ".join(deps)
                lines.append(f"\n  depends_on = [{deps_str}]")

        lines.append("}")

        # Add comment header
        header = f"""
# -----------------------------------------------------------------------------
# {cfn_name} ({cfn_type})
# -----------------------------------------------------------------------------
"""
        return header + "\n".join(lines) + "\n"

    def _generate_unsupported_resource_comment(
        self, cfn_name: str, cfn_type: str, resource_data: Dict[str, Any]
    ) -> str:
        """Generate a comment for unsupported resources."""
        properties = json.dumps(resource_data.get("Properties", {}), indent=2)
        return f"""
# -----------------------------------------------------------------------------
# UNSUPPORTED RESOURCE: {cfn_name}
# CloudFormation Type: {cfn_type}
#
# This resource type is not yet supported by the converter.
# Please manually convert this resource to Terraform.
#
# Original Properties:
# {properties}
# -----------------------------------------------------------------------------
"""

    def _convert_properties(
        self, cfn_type: str, properties: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Convert CloudFormation properties to Terraform attributes."""
        converted = {}
        property_mapping = PROPERTY_MAPPINGS.get(cfn_type, {})

        for cfn_prop, value in properties.items():
            # Get the Terraform attribute name
            tf_attr = property_mapping.get(cfn_prop, self._to_terraform_name(cfn_prop))

            # Convert the value
            converted_value = self._convert_value(value, cfn_type, cfn_prop)

            # Special handling for Tags
            if cfn_prop == "Tags" and isinstance(value, list):
                converted_value = transform_tags(value)

            # Special handling for security group rules
            if cfn_prop == "SecurityGroupIngress":
                converted_value = transform_security_group_rules(value, "ingress")
            elif cfn_prop == "SecurityGroupEgress":
                converted_value = transform_security_group_rules(value, "egress")

            if converted_value is not None:
                converted[tf_attr] = converted_value

        return converted

    def _convert_value(self, value: Any, cfn_type: str = "", cfn_prop: str = "") -> Any:
        """Convert a CloudFormation value to Terraform format."""
        if value is None:
            return None

        if isinstance(value, dict):
            # Handle intrinsic functions
            if "Ref" in value:
                return self._convert_ref(value["Ref"])
            elif "Fn::GetAtt" in value:
                return self._convert_getatt(value["Fn::GetAtt"])
            elif "Fn::Sub" in value:
                return self._convert_sub(value["Fn::Sub"])
            elif "Fn::Join" in value:
                return self._convert_join(value["Fn::Join"])
            elif "Fn::If" in value:
                return self._convert_if(value["Fn::If"])
            elif "Fn::Select" in value:
                return self._convert_select(value["Fn::Select"])
            elif "Fn::Split" in value:
                return self._convert_split(value["Fn::Split"])
            elif "Fn::Base64" in value:
                return self._convert_base64(value["Fn::Base64"])
            elif "Fn::FindInMap" in value:
                return self._convert_findinmap(value["Fn::FindInMap"])
            elif "Fn::ImportValue" in value:
                return self._convert_import_value(value["Fn::ImportValue"])
            else:
                # Recursively convert nested objects
                return {k: self._convert_value(v) for k, v in value.items()}

        elif isinstance(value, list):
            return [self._convert_value(item) for item in value]

        return value

    def _convert_ref(self, ref: str) -> str:
        """Convert Ref intrinsic function."""
        # Check if it's a pseudo-parameter
        if ref in PSEUDO_PARAMETER_MAPPING:
            self.required_data_sources.add(ref)
            return f"${{{PSEUDO_PARAMETER_MAPPING[ref]}}}"

        # Check if it's a parameter
        if ref in self.parameters:
            return f"${{var.{self._to_terraform_name(ref)}}}"

        # Check if it's a resource
        if ref in self.resources:
            resource_type = self.resources[ref].get("Type", "")
            tf_type = get_terraform_resource_type(resource_type)
            tf_name = self.resource_name_mapping.get(ref, self._to_terraform_name(ref))
            ref_attr = RESOURCE_REF_MAPPING.get(resource_type, "id")
            if tf_type:
                return f"${{{tf_type}.{tf_name}.{ref_attr}}}"

        return f"${{local.{self._to_terraform_name(ref)}}}"

    def _convert_getatt(self, getatt: Any) -> str:
        """Convert Fn::GetAtt intrinsic function."""
        if isinstance(getatt, str):
            parts = getatt.split(".")
            resource_name = parts[0]
            attribute = ".".join(parts[1:]) if len(parts) > 1 else "id"
        elif isinstance(getatt, list) and len(getatt) >= 2:
            resource_name = getatt[0]
            attribute = getatt[1]
        else:
            return str(getatt)

        if resource_name in self.resources:
            resource_type = self.resources[resource_name].get("Type", "")
            tf_type = get_terraform_resource_type(resource_type)
            tf_name = self.resource_name_mapping.get(
                resource_name, self._to_terraform_name(resource_name)
            )

            # Get the correct Terraform attribute
            attr_mapping = RESOURCE_GETATT_MAPPING.get(resource_type, {})
            tf_attr = attr_mapping.get(attribute, self._to_terraform_name(attribute))

            if tf_type:
                return f"${{{tf_type}.{tf_name}.{tf_attr}}}"

        return f"${{local.{self._to_terraform_name(resource_name)}_{self._to_terraform_name(attribute)}}}"

    def _convert_sub(self, sub: Any) -> str:
        """Convert Fn::Sub intrinsic function."""
        if isinstance(sub, str):
            template = sub
            variables = {}
        elif isinstance(sub, list) and len(sub) >= 1:
            template = sub[0]
            variables = sub[1] if len(sub) > 1 else {}
        else:
            return str(sub)

        # Replace ${} placeholders
        result = template

        # Replace variable references
        for var_name, var_value in variables.items():
            converted_value = self._convert_value(var_value)
            if isinstance(converted_value, str) and converted_value.startswith("${"):
                # Already a Terraform reference
                result = result.replace(f"${{{var_name}}}", converted_value)
            else:
                result = result.replace(f"${{{var_name}}}", str(converted_value))

        # Replace remaining ${} references (pseudo-parameters, resources, etc.)
        def replace_ref(match):
            ref_name = match.group(1)
            # Check for GetAtt syntax (Resource.Attribute)
            if "." in ref_name:
                parts = ref_name.split(".", 1)
                return self._convert_getatt(parts)
            else:
                return self._convert_ref(ref_name)

        result = re.sub(r"\$\{([^}]+)\}", replace_ref, result)

        return result

    def _convert_join(self, join: list) -> str:
        """Convert Fn::Join intrinsic function."""
        if not isinstance(join, list) or len(join) < 2:
            return str(join)

        delimiter = join[0]
        values = join[1]

        converted_values = []
        for val in values:
            converted = self._convert_value(val)
            if isinstance(converted, str):
                converted_values.append(converted)
            else:
                converted_values.append(str(converted))

        # Build join expression
        values_str = ", ".join(converted_values)
        return f'${{join("{delimiter}", [{values_str}])}}'

    def _convert_if(self, if_expr: list) -> str:
        """Convert Fn::If intrinsic function."""
        if not isinstance(if_expr, list) or len(if_expr) < 3:
            return str(if_expr)

        condition = if_expr[0]
        true_value = self._convert_value(if_expr[1])
        false_value = self._convert_value(if_expr[2])

        condition_name = self._to_terraform_name(condition)
        return f"${{local.{condition_name} ? {true_value} : {false_value}}}"

    def _convert_select(self, select: list) -> str:
        """Convert Fn::Select intrinsic function."""
        if not isinstance(select, list) or len(select) < 2:
            return str(select)

        index = select[0]
        list_value = self._convert_value(select[1])

        return f"${{element({list_value}, {index})}}"

    def _convert_split(self, split: list) -> str:
        """Convert Fn::Split intrinsic function."""
        if not isinstance(split, list) or len(split) < 2:
            return str(split)

        delimiter = split[0]
        string_value = self._convert_value(split[1])

        return f'${{split("{delimiter}", {string_value})}}'

    def _convert_base64(self, value: Any) -> str:
        """Convert Fn::Base64 intrinsic function."""
        converted = self._convert_value(value)
        return f"${{base64encode({converted})}}"

    def _convert_findinmap(self, findinmap: list) -> str:
        """Convert Fn::FindInMap intrinsic function."""
        if not isinstance(findinmap, list) or len(findinmap) < 3:
            return str(findinmap)

        map_name = self._to_terraform_name(findinmap[0])
        first_key = self._convert_value(findinmap[1])
        second_key = self._convert_value(findinmap[2])

        # Clean up the keys
        if isinstance(first_key, str) and first_key.startswith("${"):
            first_key = first_key[2:-1]
        else:
            first_key = f'"{first_key}"'

        if isinstance(second_key, str) and second_key.startswith("${"):
            second_key = second_key[2:-1]
        else:
            second_key = f'"{second_key}"'

        return f"${{local.{map_name}[{first_key}][{second_key}]}}"

    def _convert_import_value(self, value: Any) -> str:
        """Convert Fn::ImportValue intrinsic function."""
        converted = self._convert_value(value)
        # ImportValue typically references another stack's output
        # In Terraform, this would be a data source or remote state
        return f"${{data.terraform_remote_state.shared.outputs.{self._to_terraform_name(str(converted))}}}"

    def _format_property(self, name: str, value: Any, indent: int = 0) -> List[str]:
        """Format a property for HCL output."""
        prefix = " " * indent
        lines = []

        if value is None:
            return lines

        if isinstance(value, bool):
            lines.append(f"{prefix}{name} = {str(value).lower()}")
        elif isinstance(value, (int, float)):
            lines.append(f"{prefix}{name} = {value}")
        elif isinstance(value, str):
            if value.startswith("${") and value.endswith("}"):
                # Terraform expression
                lines.append(f"{prefix}{name} = {value}")
            else:
                lines.append(f'{prefix}{name} = "{self._escape_string(value)}"')
        elif isinstance(value, list):
            if all(isinstance(item, (str, int, float, bool)) for item in value):
                # Simple list
                formatted_items = []
                for item in value:
                    if isinstance(item, str):
                        if item.startswith("${"):
                            formatted_items.append(str(item))
                        else:
                            formatted_items.append(f'"{self._escape_string(str(item))}"')
                    elif isinstance(item, bool):
                        formatted_items.append(str(item).lower())
                    else:
                        formatted_items.append(str(item))
                lines.append(f"{prefix}{name} = [{', '.join([str(x) for x in formatted_items])}]")
            else:
                # Complex list - each item is a block
                for item in value:
                    if isinstance(item, dict):
                        lines.append(f"{prefix}{name} {{")
                        for k, v in item.items():
                            lines.extend(self._format_property(k, v, indent + 2))
                        lines.append(f"{prefix}}}")
        elif isinstance(value, dict):
            # Check if this should be a block or a map
            if self._is_block_type(name):
                lines.append(f"{prefix}{name} {{")
                for k, v in value.items():
                    lines.extend(self._format_property(k, v, indent + 2))
                lines.append(f"{prefix}}}")
            else:
                # Treat as a map
                lines.append(f"{prefix}{name} = {{")
                for k, v in value.items():
                    if isinstance(v, str):
                        if v.startswith("${"):
                            lines.append(f'{prefix}  {k} = {v}')
                        else:
                            lines.append(f'{prefix}  {k} = "{self._escape_string(v)}"')
                    elif isinstance(v, bool):
                        lines.append(f"{prefix}  {k} = {str(v).lower()}")
                    else:
                        lines.append(f"{prefix}  {k} = {v}")
                lines.append(f"{prefix}}}")

        return lines

    def _is_block_type(self, name: str) -> bool:
        """Check if a property should be formatted as a block."""
        block_types = {
            "ingress", "egress", "root_block_device", "ebs_block_device",
            "environment", "vpc_config", "tracing_config", "versioning",
            "logging", "website", "cors_rule", "lifecycle_rule",
            "replication_configuration", "server_side_encryption_configuration",
            "network_configuration", "load_balancer", "setting", "attribute",
            "global_secondary_index", "local_secondary_index", "ttl",
            "point_in_time_recovery", "server_side_encryption", "access_logs",
        }
        return name in block_types

    def _escape_string(self, s: str) -> str:
        """Escape special characters in strings for HCL."""
        return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    def _format_value(self, value: Any, tf_type: str) -> str:
        """Format a value for HCL based on its type."""
        if tf_type == "string":
            return f'"{self._escape_string(str(value))}"'
        elif tf_type == "number":
            return str(value)
        elif tf_type.startswith("list"):
            if isinstance(value, list):
                items = [self._format_value(v, "string") for v in value]
                return f"[{', '.join(items)}]"
            elif isinstance(value, str):
                # Comma-delimited list
                items = [f'"{self._escape_string(v.strip())}"' for v in value.split(",")]
                return f"[{', '.join(items)}]"
        elif tf_type == "bool":
            return str(value).lower()

        return f'"{self._escape_string(str(value))}"'

    def _generate_outputs(self) -> str:
        """Generate Terraform outputs from CloudFormation outputs."""
        if not self.outputs:
            return ""

        lines = ['''# =============================================================================
# Outputs
# =============================================================================
''']

        for output_name, output_data in self.outputs.items():
            tf_name = self._to_terraform_name(output_name)
            description = output_data.get("Description", "")
            value = output_data.get("Value")
            export_name = output_data.get("Export", {}).get("Name")

            lines.append(f'output "{tf_name}" {{')
            if description:
                lines.append(f'  description = "{self._escape_string(description)}"')

            converted_value = self._convert_value(value)
            if isinstance(converted_value, str) and converted_value.startswith("${"):
                lines.append(f"  value       = {converted_value}")
            else:
                lines.append(f'  value       = "{self._escape_string(str(converted_value))}"')

            lines.append("}")
            lines.append("")

        return "\n".join(lines)
