"""
User Data Generator Module

Generates EC2 user data scripts by combining templates with custom configurations.
Supports CloudFormation to Terraform user data conversion.
"""

import base64
import re
from typing import Any, Dict, List, Optional, Union

from cf2tf.userdata.templates import USERDATA_TEMPLATES, get_template


class UserDataGenerator:
    """Generator for EC2 user data scripts."""

    def __init__(self, default_shell: str = "/bin/bash"):
        """
        Initialize the UserDataGenerator.

        Args:
            default_shell: Default shell interpreter for scripts.
        """
        self.default_shell = default_shell
        self.variables: Dict[str, str] = {}
        self.scripts: List[str] = []

    def set_variables(self, variables: Dict[str, str]) -> "UserDataGenerator":
        """
        Set template variables for substitution.

        Args:
            variables: Dictionary of variable names to values.

        Returns:
            Self for method chaining.
        """
        self.variables.update(variables)
        return self

    def add_template(
        self,
        template_name: str,
        variables: Optional[Dict[str, str]] = None,
    ) -> "UserDataGenerator":
        """
        Add a template to the user data script.

        Args:
            template_name: Name of the template to add.
            variables: Optional variables specific to this template.

        Returns:
            Self for method chaining.

        Raises:
            ValueError: If template name is not found.
        """
        template = get_template(template_name)
        if template is None:
            raise ValueError(f"Template '{template_name}' not found")

        script = template["template"]

        # Apply variables
        all_vars = {**self.variables}
        if variables:
            all_vars.update(variables)

        script = self._substitute_variables(script, all_vars)
        self.scripts.append(script)
        return self

    def add_custom_script(self, script: str) -> "UserDataGenerator":
        """
        Add a custom script to the user data.

        Args:
            script: Custom shell script content.

        Returns:
            Self for method chaining.
        """
        self.scripts.append(script)
        return self

    def add_commands(self, commands: List[str]) -> "UserDataGenerator":
        """
        Add a list of shell commands.

        Args:
            commands: List of shell commands to execute.

        Returns:
            Self for method chaining.
        """
        script = "\n".join(commands)
        self.scripts.append(script)
        return self

    def generate(
        self,
        include_shebang: bool = True,
        include_header: bool = True,
    ) -> str:
        """
        Generate the complete user data script.

        Args:
            include_shebang: Whether to include shebang line.
            include_header: Whether to include a header comment.

        Returns:
            Complete user data script as a string.
        """
        parts = []

        if include_shebang:
            parts.append(f"#!{self.default_shell}")

        if include_header:
            parts.append(
                "# Generated by CF2TF User Data Generator\n"
                "# This script was automatically generated from templates\n"
                "set -e  # Exit on error\n"
            )

        parts.extend(self.scripts)
        return "\n\n".join(parts)

    def generate_base64(self) -> str:
        """
        Generate the user data script as base64 encoded string.

        Returns:
            Base64 encoded user data script.
        """
        script = self.generate()
        return base64.b64encode(script.encode("utf-8")).decode("utf-8")

    def generate_terraform(
        self,
        use_base64: bool = False,
        use_templatefile: bool = False,
        template_vars: Optional[Dict[str, str]] = None,
    ) -> str:
        """
        Generate Terraform-compatible user data configuration.

        Args:
            use_base64: Whether to encode as base64.
            use_templatefile: Whether to use templatefile function.
            template_vars: Variables for templatefile function.

        Returns:
            Terraform user_data attribute string.
        """
        script = self.generate()

        if use_templatefile:
            # Return templatefile reference
            vars_str = ""
            if template_vars:
                var_items = [f'    {k} = {v}' for k, v in template_vars.items()]
                vars_str = "{\n" + "\n".join(var_items) + "\n  }"
            else:
                vars_str = "{}"
            return f'user_data = templatefile("${{path.module}}/user_data.sh", {vars_str})'

        if use_base64:
            encoded = self.generate_base64()
            return f'user_data_base64 = "{encoded}"'

        # Use heredoc for inline script
        escaped_script = script.replace("${", "$${").replace("%{", "%%{")
        return f'user_data = <<-EOF\n{escaped_script}\nEOF'

    def reset(self) -> "UserDataGenerator":
        """
        Reset the generator state.

        Returns:
            Self for method chaining.
        """
        self.scripts = []
        self.variables = {}
        return self

    def _substitute_variables(
        self,
        script: str,
        variables: Dict[str, str],
    ) -> str:
        """
        Substitute variables in a script.

        Args:
            script: Script with {{variable}} placeholders.
            variables: Dictionary of variable values.

        Returns:
            Script with variables substituted.
        """
        result = script
        for name, value in variables.items():
            placeholder = "{{" + name + "}}"
            result = result.replace(placeholder, str(value))
        return result

    @staticmethod
    def from_cloudformation_userdata(
        cf_userdata: Union[str, Dict[str, Any]],
    ) -> str:
        """
        Convert CloudFormation UserData to Terraform format.

        Args:
            cf_userdata: CloudFormation UserData (string or Fn::Base64 dict).

        Returns:
            Terraform-compatible user data string.
        """
        if isinstance(cf_userdata, str):
            # Already a string, might be base64 encoded
            try:
                decoded = base64.b64decode(cf_userdata).decode("utf-8")
                return decoded
            except Exception:
                # Not base64, return as-is
                return cf_userdata

        if isinstance(cf_userdata, dict):
            # Handle CloudFormation intrinsic functions
            if "Fn::Base64" in cf_userdata:
                inner = cf_userdata["Fn::Base64"]
                return UserDataGenerator.from_cloudformation_userdata(inner)

            if "Fn::Join" in cf_userdata:
                delimiter, items = cf_userdata["Fn::Join"]
                converted_items = []
                for item in items:
                    if isinstance(item, str):
                        converted_items.append(item)
                    elif isinstance(item, dict):
                        # Handle Ref and GetAtt
                        converted_items.append(
                            UserDataGenerator._convert_cf_reference(item)
                        )
                return delimiter.join(converted_items)

            if "Fn::Sub" in cf_userdata:
                sub_value = cf_userdata["Fn::Sub"]
                if isinstance(sub_value, str):
                    # Simple substitution - convert ${} to Terraform format
                    return UserDataGenerator._convert_cf_sub(sub_value)
                elif isinstance(sub_value, list):
                    # Sub with variable map
                    template_str = sub_value[0]
                    var_map = sub_value[1] if len(sub_value) > 1 else {}
                    return UserDataGenerator._convert_cf_sub(template_str, var_map)

        return str(cf_userdata)

    @staticmethod
    def _convert_cf_reference(ref_dict: Dict[str, Any]) -> str:
        """
        Convert CloudFormation reference to Terraform format.

        Args:
            ref_dict: Dictionary containing Ref or Fn::GetAtt.

        Returns:
            Terraform reference string.
        """
        if "Ref" in ref_dict:
            ref_name = ref_dict["Ref"]
            # Convert to Terraform variable or resource reference
            return f"${{var.{_to_snake_case(ref_name)}}}"

        if "Fn::GetAtt" in ref_dict:
            get_att = ref_dict["Fn::GetAtt"]
            if isinstance(get_att, list):
                resource_name, attribute = get_att[0], get_att[1]
            else:
                # String format "Resource.Attribute"
                parts = get_att.split(".")
                resource_name, attribute = parts[0], parts[1]
            tf_resource = _to_snake_case(resource_name)
            tf_attr = _to_snake_case(attribute)
            return f"${{aws_resource.{tf_resource}.{tf_attr}}}"

        return str(ref_dict)

    @staticmethod
    def _convert_cf_sub(
        template_str: str,
        var_map: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Convert CloudFormation Fn::Sub template to Terraform format.

        Args:
            template_str: CloudFormation Sub template string.
            var_map: Optional variable map for the Sub function.

        Returns:
            Terraform-compatible string.
        """
        result = template_str

        # Replace ${!Literal} with literal $
        result = re.sub(r"\$\{!([^}]+)\}", r"${\1}", result)

        # Replace ${AWS::StackName} and other pseudo parameters
        pseudo_params = {
            "AWS::StackName": "local.stack_name",
            "AWS::StackId": "local.stack_id",
            "AWS::Region": "data.aws_region.current.name",
            "AWS::AccountId": "data.aws_caller_identity.current.account_id",
            "AWS::URLSuffix": "data.aws_partition.current.dns_suffix",
            "AWS::Partition": "data.aws_partition.current.partition",
        }

        for cf_param, tf_ref in pseudo_params.items():
            result = result.replace(f"${{{cf_param}}}", f"${{{tf_ref}}}")

        # Replace ${ResourceName} references
        def replace_ref(match: re.Match) -> str:
            ref_name = match.group(1)
            if var_map and ref_name in var_map:
                # Use the variable map value
                var_value = var_map[ref_name]
                if isinstance(var_value, dict):
                    return UserDataGenerator._convert_cf_reference(var_value)
                return str(var_value)
            # Convert to snake_case for Terraform
            return f"${{var.{_to_snake_case(ref_name)}}}"

        # Match ${SomeName} but not ${AWS::*} or ${!*}
        result = re.sub(r"\$\{(?!AWS::)(?!!)([\w]+)\}", replace_ref, result)

        # Replace ${ResourceName.Attribute} with Terraform GetAtt equivalent
        def replace_getatt(match: re.Match) -> str:
            resource = match.group(1)
            attribute = match.group(2)
            tf_resource = _to_snake_case(resource)
            tf_attr = _to_snake_case(attribute)
            return f"${{aws_resource.{tf_resource}.{tf_attr}}}"

        result = re.sub(r"\$\{([\w]+)\.([\w]+)\}", replace_getatt, result)

        return result


def _to_snake_case(name: str) -> str:
    """
    Convert CamelCase or PascalCase to snake_case.

    Args:
        name: String in CamelCase or PascalCase.

    Returns:
        String in snake_case.
    """
    # Insert underscore before uppercase letters
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    # Insert underscore before uppercase letters preceded by lowercase
    s2 = re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def create_userdata_for_scenario(
    scenario: str,
    **kwargs: Any,
) -> str:
    """
    Create user data for common deployment scenarios.

    Args:
        scenario: Deployment scenario name.
        **kwargs: Additional configuration options.

    Returns:
        Complete user data script.

    Available scenarios:
        - web_server: Basic web server (nginx or apache)
        - docker_host: Docker host with optional compose
        - kubernetes_node: Kubernetes worker node
        - monitoring_agent: CloudWatch or Prometheus agent
        - database_server: MySQL or PostgreSQL server
    """
    generator = UserDataGenerator()

    if scenario == "web_server":
        os_type = kwargs.get("os", "amazon-linux-2")
        web_server = kwargs.get("server", "nginx")

        if os_type == "ubuntu":
            generator.add_template("base-ubuntu")
        else:
            generator.add_template("base-amazon-linux-2")

        if web_server == "apache":
            generator.add_template("webserver-apache")
        else:
            generator.add_template("webserver-nginx")

        if kwargs.get("monitoring", False):
            generator.add_template("monitoring-cloudwatch-agent")

    elif scenario == "docker_host":
        os_type = kwargs.get("os", "amazon-linux-2")

        if os_type == "ubuntu":
            generator.add_template("base-ubuntu")
        else:
            generator.add_template("base-amazon-linux-2")

        generator.add_template("container-docker")

        if kwargs.get("monitoring", False):
            generator.add_template("monitoring-cloudwatch-agent")

    elif scenario == "kubernetes_node":
        os_type = kwargs.get("os", "amazon-linux-2")

        if os_type == "ubuntu":
            generator.add_template("base-ubuntu")
        else:
            generator.add_template("base-amazon-linux-2")

        generator.add_template("container-docker")
        generator.add_template(
            "container-kubernetes-node",
            {"CLUSTER_NAME": kwargs.get("cluster_name", "my-cluster")},
        )

    elif scenario == "monitoring_agent":
        os_type = kwargs.get("os", "amazon-linux-2")
        agent_type = kwargs.get("agent", "cloudwatch")

        if os_type == "ubuntu":
            generator.add_template("base-ubuntu")
        else:
            generator.add_template("base-amazon-linux-2")

        if agent_type == "prometheus":
            generator.add_template("monitoring-prometheus-node-exporter")
        else:
            generator.add_template("monitoring-cloudwatch-agent")

    elif scenario == "database_server":
        os_type = kwargs.get("os", "amazon-linux-2")
        db_type = kwargs.get("database", "mysql")

        if os_type == "ubuntu":
            generator.add_template("base-ubuntu")
        else:
            generator.add_template("base-amazon-linux-2")

        if db_type == "postgresql":
            generator.add_template("database-postgresql")
        else:
            generator.add_template("database-mysql")

        if kwargs.get("hardening", True):
            generator.add_template("security-hardening-base")

    else:
        raise ValueError(f"Unknown scenario: {scenario}")

    # Add security hardening if requested
    if kwargs.get("security_hardening", False) and scenario != "database_server":
        generator.add_template("security-hardening-base")

    # Add fail2ban if requested
    if kwargs.get("fail2ban", False):
        generator.add_template("security-fail2ban")

    return generator.generate()
